import lottie from 'lottie-web';
class BodyMoving {
    constructor() {
        this.bodymovingwrap = document.querySelectorAll('.bodymoving');
        this.animationData = {
            v: '5.7.12',
            fr: 24,
            ip: 0,
            op: 49,
            w: 500,
            h: 500,
            nm: 'Triad-Lines',
            ddd: 0,
            assets: [],
            layers: [
                {
                    ddd: 0,
                    ind: 4,
                    ty: 3,
                    nm: 'NULL CONTROL ',
                    sr: 1,
                    ks: {
                        o: { a: 0, k: 0, ix: 11 },
                        r: { a: 0, k: 0, ix: 10 },
                        p: { a: 0, k: [205.25, 302.5, 0], ix: 2, l: 2 },
                        a: { a: 0, k: [50, 50, 0], ix: 1, l: 2 },
                        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
                    },
                    ao: 0,
                    ip: 0,
                    op: 96,
                    st: 0,
                    bm: 0,
                },
                {
                    ddd: 0,
                    ind: 5,
                    ty: 4,
                    nm: 'Triad-Lines Outlines 2',
                    parent: 4,
                    sr: 1,
                    ks: {
                        o: { a: 0, k: 100, ix: 11 },
                        r: { a: 0, k: 0, ix: 10 },
                        p: { a: 0, k: [50, 50, 0], ix: 2, l: 2 },
                        a: { a: 0, k: [205, 205, 0], ix: 1, l: 2 },
                        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
                    },
                    ao: 0,
                    shapes: [
                        {
                            ty: 'gr',
                            it: [
                                {
                                    ind: 0,
                                    ty: 'sh',
                                    ix: 1,
                                    ks: {
                                        a: 0,
                                        k: {
                                            i: [
                                                [0, 0],
                                                [0, 0],
                                            ],
                                            o: [
                                                [0, 0],
                                                [0, 0],
                                            ],
                                            v: [
                                                [154.904, -158.306],
                                                [-154.904, 158.306],
                                            ],
                                            c: false,
                                        },
                                        ix: 2,
                                    },
                                    nm: 'Path 1',
                                    mn: 'ADBE Vector Shape - Group',
                                    hd: false,
                                },
                                {
                                    ty: 'st',
                                    c: { a: 0, k: [0.866666726505, 0.729411764706, 0.498039245605, 1], ix: 3 },
                                    o: { a: 0, k: 100, ix: 4 },
                                    w: { a: 0, k: 8, ix: 5 },
                                    lc: 1,
                                    lj: 1,
                                    ml: 4,
                                    bm: 0,
                                    nm: 'Stroke 1',
                                    mn: 'ADBE Vector Graphic - Stroke',
                                    hd: false,
                                },
                                {
                                    ty: 'tr',
                                    p: { a: 0, k: [316.813, 66.165], ix: 2 },
                                    a: { a: 0, k: [0, 0], ix: 1 },
                                    s: { a: 0, k: [100, 100], ix: 3 },
                                    r: { a: 0, k: 0, ix: 6 },
                                    o: { a: 0, k: 100, ix: 7 },
                                    sk: { a: 0, k: 0, ix: 4 },
                                    sa: { a: 0, k: 0, ix: 5 },
                                    nm: 'Transform',
                                },
                            ],
                            nm: 'Group 2',
                            np: 2,
                            cix: 2,
                            bm: 0,
                            ix: 1,
                            mn: 'ADBE Vector Group',
                            hd: false,
                        },
                        {
                            ty: 'tm',
                            s: {
                                a: 1,
                                k: [
                                    { i: { x: [0.4], y: [1] }, o: { x: [0.167], y: [0] }, t: 0, s: [0] },
                                    { t: 20, s: [0] },
                                ],
                                ix: 1,
                            },
                            e: {
                                a: 1,
                                k: [
                                    { i: { x: [0.4], y: [1] }, o: { x: [0.6], y: [0] }, t: 0, s: [0] },
                                    { t: 20, s: [100] },
                                ],
                                ix: 2,
                            },
                            o: { a: 0, k: 0, ix: 3 },
                            m: 1,
                            ix: 2,
                            nm: 'Trim Paths 1',
                            mn: 'ADBE Vector Filter - Trim',
                            hd: false,
                        },
                    ],
                    ip: 0,
                    op: 96,
                    st: 3,
                    bm: 0,
                },
                {
                    ddd: 0,
                    ind: 6,
                    ty: 4,
                    nm: 'Triad-Lines Outlines',
                    parent: 4,
                    sr: 1,
                    ks: {
                        o: { a: 0, k: 100, ix: 11 },
                        r: { a: 0, k: 0, ix: 10 },
                        p: { a: 0, k: [50, 50, 0], ix: 2, l: 2 },
                        a: { a: 0, k: [205, 205, 0], ix: 1, l: 2 },
                        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
                    },
                    ao: 0,
                    shapes: [
                        {
                            ty: 'gr',
                            it: [
                                {
                                    ind: 0,
                                    ty: 'sh',
                                    ix: 1,
                                    ks: {
                                        a: 0,
                                        k: {
                                            i: [
                                                [0, 0],
                                                [0, 0],
                                            ],
                                            o: [
                                                [0, 0],
                                                [0, 0],
                                            ],
                                            v: [
                                                [154.904, -158.305],
                                                [-154.904, 158.305],
                                            ],
                                            c: false,
                                        },
                                        ix: 2,
                                    },
                                    nm: 'Path 1',
                                    mn: 'ADBE Vector Shape - Group',
                                    hd: false,
                                },
                                {
                                    ty: 'st',
                                    c: { a: 0, k: [0.866666726505, 0.729411764706, 0.498039245605, 1], ix: 3 },
                                    o: { a: 0, k: 100, ix: 4 },
                                    w: { a: 0, k: 8, ix: 5 },
                                    lc: 1,
                                    lj: 1,
                                    ml: 4,
                                    bm: 0,
                                    nm: 'Stroke 1',
                                    mn: 'ADBE Vector Graphic - Stroke',
                                    hd: false,
                                },
                                {
                                    ty: 'tr',
                                    p: { a: 0, k: [192.866, 229.522], ix: 2 },
                                    a: { a: 0, k: [0, 0], ix: 1 },
                                    s: { a: 0, k: [100, 100], ix: 3 },
                                    r: { a: 0, k: 0, ix: 6 },
                                    o: { a: 0, k: 100, ix: 7 },
                                    sk: { a: 0, k: 0, ix: 4 },
                                    sa: { a: 0, k: 0, ix: 5 },
                                    nm: 'Transform',
                                },
                            ],
                            nm: 'Group 3',
                            np: 2,
                            cix: 2,
                            bm: 0,
                            ix: 1,
                            mn: 'ADBE Vector Group',
                            hd: false,
                        },
                        {
                            ty: 'tm',
                            s: {
                                a: 1,
                                k: [
                                    { i: { x: [0.4], y: [1] }, o: { x: [0.6], y: [0] }, t: 0, s: [0] },
                                    { t: 19, s: [0] },
                                ],
                                ix: 1,
                            },
                            e: {
                                a: 1,
                                k: [
                                    { i: { x: [0.833], y: [1] }, o: { x: [0.6], y: [0] }, t: 0, s: [0] },
                                    { t: 19, s: [100] },
                                ],
                                ix: 2,
                            },
                            o: { a: 0, k: 0, ix: 3 },
                            m: 1,
                            ix: 2,
                            nm: 'Trim Paths 1',
                            mn: 'ADBE Vector Filter - Trim',
                            hd: false,
                        },
                    ],
                    ip: 0,
                    op: 100,
                    st: 10,
                    bm: 0,
                },
                {
                    ddd: 0,
                    ind: 7,
                    ty: 4,
                    nm: 'Triad-Lines Outlines 3',
                    parent: 4,
                    sr: 1,
                    ks: {
                        o: { a: 0, k: 100, ix: 11 },
                        r: { a: 0, k: 0, ix: 10 },
                        p: { a: 0, k: [50, 50, 0], ix: 2, l: 2 },
                        a: { a: 0, k: [205, 205, 0], ix: 1, l: 2 },
                        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
                    },
                    ao: 0,
                    shapes: [
                        {
                            ty: 'gr',
                            it: [
                                {
                                    ind: 0,
                                    ty: 'sh',
                                    ix: 1,
                                    ks: {
                                        a: 0,
                                        k: {
                                            i: [
                                                [0, 0],
                                                [0, 0],
                                            ],
                                            o: [
                                                [0, 0],
                                                [0, 0],
                                            ],
                                            v: [
                                                [154.903, -158.305],
                                                [-154.903, 158.305],
                                            ],
                                            c: false,
                                        },
                                        ix: 2,
                                    },
                                    nm: 'Path 1',
                                    mn: 'ADBE Vector Shape - Group',
                                    hd: false,
                                },
                                {
                                    ty: 'st',
                                    c: { a: 0, k: [0.866666726505, 0.729411764706, 0.498039245605, 1], ix: 3 },
                                    o: { a: 0, k: 100, ix: 4 },
                                    w: { a: 0, k: 8, ix: 5 },
                                    lc: 1,
                                    lj: 1,
                                    ml: 4,
                                    bm: 0,
                                    nm: 'Stroke 1',
                                    mn: 'ADBE Vector Graphic - Stroke',
                                    hd: false,
                                },
                                {
                                    ty: 'tr',
                                    p: { a: 0, k: [289.545, 167.409], ix: 2 },
                                    a: { a: 0, k: [0, 0], ix: 1 },
                                    s: { a: 0, k: [100, 100], ix: 3 },
                                    r: { a: 0, k: 0, ix: 6 },
                                    o: { a: 0, k: 100, ix: 7 },
                                    sk: { a: 0, k: 0, ix: 4 },
                                    sa: { a: 0, k: 0, ix: 5 },
                                    nm: 'Transform',
                                },
                            ],
                            nm: 'Group 1',
                            np: 2,
                            cix: 2,
                            bm: 0,
                            ix: 1,
                            mn: 'ADBE Vector Group',
                            hd: false,
                        },
                        {
                            ty: 'tm',
                            s: { a: 0, k: 100, ix: 1 },
                            e: {
                                a: 1,
                                k: [
                                    { i: { x: [0.4], y: [1] }, o: { x: [0.6], y: [0] }, t: 0, s: [100] },
                                    { t: 18, s: [0] },
                                ],
                                ix: 2,
                            },
                            o: {
                                a: 1,
                                k: [
                                    { i: { x: [0.4], y: [1] }, o: { x: [0.6], y: [0] }, t: 0, s: [0] },
                                    { t: 18, s: [0] },
                                ],
                                ix: 3,
                            },
                            m: 1,
                            ix: 2,
                            nm: 'Trim Paths 1',
                            mn: 'ADBE Vector Filter - Trim',
                            hd: false,
                        },
                    ],
                    ip: 0,
                    op: 104,
                    st: 8,
                    bm: 0,
                },
            ],
            markers: [],
        };
        this.init();
    }

    init() {
        // this.bodymovingwrap.length;
        this.bodymovingwrap.forEach((el) => {
            lottie.loadAnimation({
                container: el.querySelector('.js-bodymoving'),
                renderer: 'svg',
                loop: true,
                autoplay: true,
                path: el.querySelector('.js-bodymoving').dataset.path,
            });
        });
    }
}

export default BodyMoving;
